CREATE TABLE Referee (
refereeID INT(6) AUTO_INCREMENT PRIMARY KEY,
firstname VARCHAR(30) NOT NULL,
lastname VARCHAR(30) NOT NULL,
grade VARCHAR(50),
rating VARCHAR(50),
dob DATE NOT NULL
);

CREATE TABLE User (
userID INT(6) AUTO_INCREMENT PRIMARY KEY,
user_role VARCHAR(30) NOT NULL,
user_password VARCHAR(30) NOT NULL
);

CREATE TABLE Game (
gameID INT(6) AUTO_INCREMENT PRIMARY KEY,
field VARCHAR(30) NOT NULL,
game_name VARCHAR(30) NOT NULL,
game_time TIME NOT NULL
);

CREATE TABLE Ref_Game (
rg_status VARCHAR(30) NOT NULL,
postion VARCHAR(30) NOT NULL,
refereeID INT(6) NOT NULL,
FOREIGN KEY (refereeID) REFERENCES Referee(refereeID),
gameID INT(6) NOT NULL,
FOREIGN KEY (gameID) REFERENCES Game(gameID)
);